version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/Matts966/genelizer
    environment:
      GO111MODULE: "on"
workflows:
  build:
    jobs:
      - build
jobs:
  build:
    executor:
      name: default
    working_directory: /go/src/github.com/Matts966/genelizer
    steps:
      - checkout
      - restore_dep
      - install_dep 
      - save_dep
      - test
      - run:
          command: |
            go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
      - codecov/upload:
        file: ./coverage.out
orbs:
  codecov: codecov/codecov@1.0.5
commands:
  restore_dep:
    steps:
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
  save_dep:
    steps:
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/cache
  install_dep:
    steps:
      - run:
          name: Installing dependencies
          command: go mod download
  test:
    steps:
      - run:
          name: Run test
          command: go test -v ./...
