// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d4f89177d24133c2e3647842fa86fea0"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"b112c8b952e98718469700b23b40b140": "1f8b08000000000000ff2a2acd4955502a4a4dcb494d2e5152a8e65250505028484cce4e4c4f55b045c880c573538b8ba1e219a9958a10c194fc641085a45821392335393bb54889ab968b0b62414e7e3a16c341a244199c939f8ec5d0b45c6c2e06891265685a2e8a4b01010000ffff023795ef0a010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Config", "../config")
		b.SetResolver("sample.hcl", packr.Pointer{ForwardBox: gk, ForwardPath: "b112c8b952e98718469700b23b40b140"})
		}()

	return nil
}()
