// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d4f89177d24133c2e3647842fa86fea0"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"80a62026e981e6102aa0a3ce03a5c13e": "1f8b08000000000000ffac90c14a04311044eff31545fe630fea49bc088b5ec443dbe9ac6142477a132f32ff2e3371c22e2b2c039b63baea55515693c09984245c98d4e16700802fe2910e825d3fbae5df679efff85378049322542d312be2114c29896fba5095e11eb588056259b1f3336189df6233e7955215d74f1f12b209dc03e9a9755a04d309f8ce7bdbcefc735de2f652b6d39a69854dc370b6e518d56f1a73319c777ace715e6163b5a7968c7e68be524db1c31bdc8b1e294887bf77e1bfc3dce79c6edda031af04ef8b453ddc3a7aa55e864fc36f000000ffffe1ae47860d030000",
		"c71dab62dd58b5bc2cb6640d2cedfff0": "1f8b08000000000000ff34ce314b04410c05e07e7fc523a5c8a517aeb3b1d5522cc6d9383bdc3a09930ca272ff5d76d74b17f285f798e122b0e42ecea379a8d5908edab044983f30971acb783f65fde4926d14fe49253599fa5805742c84df09002ce54b2a823328af3ae653512dab1ccfca6ea935e9b4db59f3ee16c917d40f6cb929b4a33ab61e26f301e3db0474f7ac5f4fffe416b78d2f3ad61967bcd2a3d23de825d4e86dbf5fa7ebf4170000ffff271aec9ae3000000",
		"c97a40381df114b388a730662326743f": "1f8b08000000000000ff4ccc410ac2400c85e1fd9ce227f7e84af012e2a264523b7420c5d88548ef2e19376697f73edef3e8862cad9bf02900fbacdbfc3026c44346545df3d5d574a32d24a705da3dacfeccebbd1b72fd1bca8bd58f5e99b82197d4c27d946739cb370000ffff011b56e07c000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Config", "../config")
		b.SetResolver("file.hcl", packr.Pointer{ForwardBox: gk, ForwardPath: "c97a40381df114b388a730662326743f"})
		b.SetResolver("refsafe.hcl", packr.Pointer{ForwardBox: gk, ForwardPath: "80a62026e981e6102aa0a3ce03a5c13e"})
		b.SetResolver("zagane.hcl", packr.Pointer{ForwardBox: gk, ForwardPath: "c71dab62dd58b5bc2cb6640d2cedfff0"})
		}()

	return nil
}()
